sonar.projectKey=dgNeWork_concompas-taxista
sonar.organization=dgnework

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/*.spec.ts,**/*.spec.tsx,coverage/**

sonar.tests=.
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
